# .readthedocs.yaml
# Read the Docs configuration file for AuraTrace

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  builder: html

# Optional: Set the docs directory as the documentation root
# If using mkdocs or a different static site generator, adjust accordingly

formats:
  - html

# Optionally, set environment variables for builds
# env:
#   - AURATRACE_LLM_PROVIDER=huggingface

# Entry point for docs (if using Sphinx)
# If using mkdocs, change to mkdocs.yml

# For more info: https://docs.readthedocs.io/en/stable/config-file/v2.html 